name: Version Guard

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run version normalization in dry-run mode
        id: bump
        run: |
          python scripts/bump_doc_versions.py --dry-run > audit.log || true
          cat audit.log
          echo "-----"
          echo "Checking for version drift..."
          # Detect only version drift or non-semantic changes, ignore lastReviewed-only updates
          if grep -E "→" audit.log | grep -Ev "→ [0-9]+\.[0-9]+\.[0-9]+$" > /dev/null; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail if version drift detected
        if: steps.bump.outputs.changes == 'true'
        run: |
          echo "❌ Version metadata drift detected."
          echo "   One or more documents contain user-edited or invalid 'version' tags."
          echo "   The 'version' field is immutable and governed automatically by repository tooling."
          echo ""
          echo "   ✅ Manual edits to 'lastReviewed' are allowed."
          echo ""
          echo "   To preview normalization locally, run:"
          echo "      python scripts/bump_doc_versions.py --dry-run"
          echo ""
          echo "   Immutable version prefix (repoVersion):"
          cat version.json | grep repoVersion
          echo ""
          echo "   For details, see audit.log above."
          exit 1
