name: Doc Version Auto-Bump (CI)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-doc-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run CI version bump
        run: python scripts/bump_doc_versions.py

      - name: Commit and push bump (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: normalize doc versions"
            git push origin main
          else
            echo "No changes to commit."
          fi
